name: Android CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Build Debug APK
        run: |
          cd app
          ./gradlew assembleDebug --no-daemon
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ai-agent-apk
          path: app/build/outputs/apk/debug/*.apk